### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by ik-epm** [ik-epm/seafight-a#1]

**Comment by ik-epm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Создать Readme](https://trello.com/c/8WiXDVg2/2-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-readme)

**Comment by ik-epm** [comment]
merged and closed

**Comment by draconical** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать обработку запроса от клиента](https://trello.com/c/4fgyydGs/5-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D1%83-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0-%D0%BE%D1%82-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0)
